extends:
  - airbnb-base
  - plugin:ava/recommended

parser: babel-eslint

parserOptions:
  ecmaVersion: 2019
  sourceType: module

env:
  node: true

plugins:
  - ava
  - import
  - types

rules:
  no-console: off
  types/assign-type: error
  types/array-type: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
